### ISSUE TITLE
CSS CHECKLIST: PT 1: CSS Topics

### ISSUE THREAD

**Issue by sophiaallui** [sophiaallui/sp21-cse110-lab3#2]
- [x] Comment /* write down comments to make your css easier to read */

- [x] Color                                               /* apply colors to your HTML elements */
- [x] rgb(r, g, b) or rgba(r, g, b, a)     /* red, green, blue, alpha values */
- [x] #FFF or #FFFFFF                    /* hex codes */
- [x] hsl(h, s, l) or hsla(h, s, l, a)       /* hue, saturation, lightness, alpha values */
- [x] Color name (i.e ‘orange’)

- [x] Background     (Links to an external site.)/* apply background styles to your elements */
- [x] background-color

- [x] Unit (Links to an external site.)     /* units of measurement for sizing and spacing your elements */
- [x] Use 3 unique relative units total
- [x] Use 3 unique absolute units total

- [x] Box Model (Links to an external site.)     /* configure the containers that holds your HTML content */
- [x] (“long” and “short” refer to longhand and shorthand syntax and should give the same results. They’re simply different ways to declare your style rules, use at least one of each syntax) 
- [x] Margin     /* spacing between html elements */
- [x] Long (margin-top, margin-bottom, margin-left, margin-right)
- [x] Short (margin: <top> <right> <bottom> <left>)
- [x] Auto margins: margin: auto

- [x] Padding     /* spacing within html elements */
- [x] Long (padding-top, padding-bottom, padding-left, padding-right)
- [x] Short (padding: <top> <right> <bottom> <left>)
 
- [x] Borders (Links to an external site.)     /* borders around html elements, hint: apply borders before testing out padding and margin to better understand the difference between the two */
- [x] border-style
- [x] border-color
- [x] border-width
- [x] border-radius
- [x] Text     /* style your text */
- [x] color
- [x] text-decoration
- [x] text-align
- [x] Display (Links to an external site.)
- [x] Experiment with these values: none, block, inline-block, inline. Include at least two of them in your page.
- [x] Apply theses values to the display property
- [x] Sizing     /* set the height and width for an element */
- [x] height / width
- [x] max-width / min-width     /* add sizing constraints for responsive web pages */
- [x] Position (Links to an external site.)     /* element positioning on the page */
- [x] Experiment with these values: static, relative, fixed, absolute, sticky. Include at least two of them in your page.
- [x] Apply these values to the position property
- [x] Pseudo-class (Links to an external site.)     /* elements that exist in your document conditionally */
- [x] :hover
- [x] :active
- [x] Layouts
- [x] Flexbox (Links to an external site.)   /* allow your elements to lay themselves out automatically */
- [x] apply flex to the display property
- [x] Must have more than two children within the element that is using flexbox. Must use minimum three of the flexbox related attributes
- [x] Grid  (Links to an external site.)        /* instantiate a grid for your layouts */
- [x] apply grid to the display property
- [x] Must have more than two children within the element that is using the grid. Must use a minimum of three of the grid related attributes
- [x] Responsiveness       /* make your website friendly for multiple devices */
- [x] At least one query based on the screen width
- [x] Media Query (Links to an external site.)
- [x] Fonts (Links to an external site.)       /* pick varying font styles to make your text fun to read */
- [x] Include and use a 3rd party font (https://fonts.google.com/ (Links to an external site.)). You can load the font in either your HTML or your CSS
